# when creating new sql migrations, this will send all messages successful or failure of the migration
changeLogFile=src/main/db/changelog/db.changelog-master.yml
url=jdbc:mysql://localhost/board
username=root
password=admin@123
driver.mysql.cj.jdbc.Driver